### Site info:
name: John Didion
author: John Didion
title: John Didion's Blog
tagline: Data+Science
description: Genomics, Software, and Various Other Bits
email: <first><last> AT gmail DOT com
keywords: "data, science, code"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://john.didion.net" # the base hostname & protocol for your site
avatar: "https://avatars3.githubusercontent.com/u/125854?v=4"

### Personal info and site tools info:
twitter_username: jdidion
github_username:  jdidion
orcid_id:         0000-0002-8111-6261   
gscholar_user:    hik7qrwAAAAJ
aboutme:          "I am a computational biologist with a background in software engineering and experience in high-throughput sequencing, biological data analysis, and cloud technologies. Currently, I am a Principal Scientist @<a href='https://dnanexus.com'>DNAnexus</a>."
aboutme_photo:    "images/photo.jpeg"
favicon:          "images/favicon.ico"
resume:           "assets/JohnDidion_Resume.pdf"

### Site setting:
ShowContactInfo: "True" 
default_column: "two" 
default_locale: "en"

locales:
    en:
      Archives: "Archives"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
      Deets: Deets

### Build settings
version: v1.2.0
markdown: kramdown
paginate: 5

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: :highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME